# Generated by Django 4.2.1 on 2023-08-07 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('certification', models.CharField(max_length=20, null=True)),
                ('position', models.CharField(choices=[('software', ' Software'), ('ai', 'Ai'), ('manager', 'Manager')], default='ai', max_length=20)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('panding', ' Panding'), ('cancelled', 'Cancelled')], default='panding', max_length=20)),
                ('type', models.CharField(choices=[('ai', 'Ai'), ('other', 'Other')], default='other', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('employees', models.ManyToManyField(to='appAI.employee')),
            ],
        ),
        migrations.CreateModel(
            name='project_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appAI.employee')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAI.project_general')),
            ],
        ),
    ]
