# Generated by Django 4.2.1 on 2023-08-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_general',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
